/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NftRouteImport } from './routes/_nft'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as NftIndexRouteImport } from './routes/_nft/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as NftWalletIndexRouteImport } from './routes/_nft/wallet/index'
import { Route as NftTermsAndConditionsIndexRouteImport } from './routes/_nft/terms-and-conditions/index'
import { Route as NftProjectOverviewIndexRouteImport } from './routes/_nft/project-overview/index'
import { Route as NftOrbitIndexRouteImport } from './routes/_nft/orbit/index'
import { Route as NftOpenAiIndexRouteImport } from './routes/_nft/open-ai/index'
import { Route as NftMintedIndexRouteImport } from './routes/_nft/minted/index'
import { Route as NftLunarOriginsIndexRouteImport } from './routes/_nft/lunar-origins/index'
import { Route as NftLunarCalendarIndexRouteImport } from './routes/_nft/lunar-calendar/index'
import { Route as NftFeaturesIndexRouteImport } from './routes/_nft/features/index'
import { Route as NftFavoritesIndexRouteImport } from './routes/_nft/favorites/index'
import { Route as NftContractInterfaceIndexRouteImport } from './routes/_nft/contract-interface/index'
import { Route as NftContractEventsIndexRouteImport } from './routes/_nft/contract-events/index'
import { Route as NftAttributesIndexRouteImport } from './routes/_nft/attributes/index'
import { Route as NftAllIndexRouteImport } from './routes/_nft/all/index'
import { Route as NftIdIndexRouteImport } from './routes/_nft/$id/index'
import { Route as NftMoontotemIdRouteImport } from './routes/_nft/moontotem.$id'
import { Route as AuthenticatedAppHomeIndexRouteImport } from './routes/_authenticated/_app/home/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NftRoute = NftRouteImport.update({
  id: '/_nft',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const NftIndexRoute = NftIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NftRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const NftWalletIndexRoute = NftWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => NftRoute,
} as any)
const NftTermsAndConditionsIndexRoute =
  NftTermsAndConditionsIndexRouteImport.update({
    id: '/terms-and-conditions/',
    path: '/terms-and-conditions/',
    getParentRoute: () => NftRoute,
  } as any)
const NftProjectOverviewIndexRoute = NftProjectOverviewIndexRouteImport.update({
  id: '/project-overview/',
  path: '/project-overview/',
  getParentRoute: () => NftRoute,
} as any)
const NftOrbitIndexRoute = NftOrbitIndexRouteImport.update({
  id: '/orbit/',
  path: '/orbit/',
  getParentRoute: () => NftRoute,
} as any)
const NftOpenAiIndexRoute = NftOpenAiIndexRouteImport.update({
  id: '/open-ai/',
  path: '/open-ai/',
  getParentRoute: () => NftRoute,
} as any)
const NftMintedIndexRoute = NftMintedIndexRouteImport.update({
  id: '/minted/',
  path: '/minted/',
  getParentRoute: () => NftRoute,
} as any)
const NftLunarOriginsIndexRoute = NftLunarOriginsIndexRouteImport.update({
  id: '/lunar-origins/',
  path: '/lunar-origins/',
  getParentRoute: () => NftRoute,
} as any)
const NftLunarCalendarIndexRoute = NftLunarCalendarIndexRouteImport.update({
  id: '/lunar-calendar/',
  path: '/lunar-calendar/',
  getParentRoute: () => NftRoute,
} as any)
const NftFeaturesIndexRoute = NftFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => NftRoute,
} as any)
const NftFavoritesIndexRoute = NftFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => NftRoute,
} as any)
const NftContractInterfaceIndexRoute =
  NftContractInterfaceIndexRouteImport.update({
    id: '/contract-interface/',
    path: '/contract-interface/',
    getParentRoute: () => NftRoute,
  } as any)
const NftContractEventsIndexRoute = NftContractEventsIndexRouteImport.update({
  id: '/contract-events/',
  path: '/contract-events/',
  getParentRoute: () => NftRoute,
} as any)
const NftAttributesIndexRoute = NftAttributesIndexRouteImport.update({
  id: '/attributes/',
  path: '/attributes/',
  getParentRoute: () => NftRoute,
} as any)
const NftAllIndexRoute = NftAllIndexRouteImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => NftRoute,
} as any)
const NftIdIndexRoute = NftIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => NftRoute,
} as any)
const NftMoontotemIdRoute = NftMoontotemIdRouteImport.update({
  id: '/moontotem/$id',
  path: '/moontotem/$id',
  getParentRoute: () => NftRoute,
} as any)
const AuthenticatedAppHomeIndexRoute =
  AuthenticatedAppHomeIndexRouteImport.update({
    id: '/home/',
    path: '/home/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof NftIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/moontotem/$id': typeof NftMoontotemIdRoute
  '/$id/': typeof NftIdIndexRoute
  '/all/': typeof NftAllIndexRoute
  '/attributes/': typeof NftAttributesIndexRoute
  '/contract-events/': typeof NftContractEventsIndexRoute
  '/contract-interface/': typeof NftContractInterfaceIndexRoute
  '/favorites/': typeof NftFavoritesIndexRoute
  '/features/': typeof NftFeaturesIndexRoute
  '/lunar-calendar/': typeof NftLunarCalendarIndexRoute
  '/lunar-origins/': typeof NftLunarOriginsIndexRoute
  '/minted/': typeof NftMintedIndexRoute
  '/open-ai/': typeof NftOpenAiIndexRoute
  '/orbit/': typeof NftOrbitIndexRoute
  '/project-overview/': typeof NftProjectOverviewIndexRoute
  '/terms-and-conditions/': typeof NftTermsAndConditionsIndexRoute
  '/wallet/': typeof NftWalletIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/home/': typeof AuthenticatedAppHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof NftIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/moontotem/$id': typeof NftMoontotemIdRoute
  '/$id': typeof NftIdIndexRoute
  '/all': typeof NftAllIndexRoute
  '/attributes': typeof NftAttributesIndexRoute
  '/contract-events': typeof NftContractEventsIndexRoute
  '/contract-interface': typeof NftContractInterfaceIndexRoute
  '/favorites': typeof NftFavoritesIndexRoute
  '/features': typeof NftFeaturesIndexRoute
  '/lunar-calendar': typeof NftLunarCalendarIndexRoute
  '/lunar-origins': typeof NftLunarOriginsIndexRoute
  '/minted': typeof NftMintedIndexRoute
  '/open-ai': typeof NftOpenAiIndexRoute
  '/orbit': typeof NftOrbitIndexRoute
  '/project-overview': typeof NftProjectOverviewIndexRoute
  '/terms-and-conditions': typeof NftTermsAndConditionsIndexRoute
  '/wallet': typeof NftWalletIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/home': typeof AuthenticatedAppHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_nft': typeof NftRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_nft/': typeof NftIndexRoute
  '/_nft/moontotem/$id': typeof NftMoontotemIdRoute
  '/_nft/$id/': typeof NftIdIndexRoute
  '/_nft/all/': typeof NftAllIndexRoute
  '/_nft/attributes/': typeof NftAttributesIndexRoute
  '/_nft/contract-events/': typeof NftContractEventsIndexRoute
  '/_nft/contract-interface/': typeof NftContractInterfaceIndexRoute
  '/_nft/favorites/': typeof NftFavoritesIndexRoute
  '/_nft/features/': typeof NftFeaturesIndexRoute
  '/_nft/lunar-calendar/': typeof NftLunarCalendarIndexRoute
  '/_nft/lunar-origins/': typeof NftLunarOriginsIndexRoute
  '/_nft/minted/': typeof NftMintedIndexRoute
  '/_nft/open-ai/': typeof NftOpenAiIndexRoute
  '/_nft/orbit/': typeof NftOrbitIndexRoute
  '/_nft/project-overview/': typeof NftProjectOverviewIndexRoute
  '/_nft/terms-and-conditions/': typeof NftTermsAndConditionsIndexRoute
  '/_nft/wallet/': typeof NftWalletIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_app/home/': typeof AuthenticatedAppHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/callback'
    | '/moontotem/$id'
    | '/$id/'
    | '/all/'
    | '/attributes/'
    | '/contract-events/'
    | '/contract-interface/'
    | '/favorites/'
    | '/features/'
    | '/lunar-calendar/'
    | '/lunar-origins/'
    | '/minted/'
    | '/open-ai/'
    | '/orbit/'
    | '/project-overview/'
    | '/terms-and-conditions/'
    | '/wallet/'
    | '/auth/login/'
    | '/auth/register/'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/callback'
    | '/moontotem/$id'
    | '/$id'
    | '/all'
    | '/attributes'
    | '/contract-events'
    | '/contract-interface'
    | '/favorites'
    | '/features'
    | '/lunar-calendar'
    | '/lunar-origins'
    | '/minted'
    | '/open-ai'
    | '/orbit'
    | '/project-overview'
    | '/terms-and-conditions'
    | '/wallet'
    | '/auth/login'
    | '/auth/register'
    | '/home'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_nft'
    | '/auth'
    | '/_authenticated/_app'
    | '/auth/callback'
    | '/_nft/'
    | '/_nft/moontotem/$id'
    | '/_nft/$id/'
    | '/_nft/all/'
    | '/_nft/attributes/'
    | '/_nft/contract-events/'
    | '/_nft/contract-interface/'
    | '/_nft/favorites/'
    | '/_nft/features/'
    | '/_nft/lunar-calendar/'
    | '/_nft/lunar-origins/'
    | '/_nft/minted/'
    | '/_nft/open-ai/'
    | '/_nft/orbit/'
    | '/_nft/project-overview/'
    | '/_nft/terms-and-conditions/'
    | '/_nft/wallet/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_app/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  NftRoute: typeof NftRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nft': {
      id: '/_nft'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nft/': {
      id: '/_nft/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NftIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_nft/wallet/': {
      id: '/_nft/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof NftWalletIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/terms-and-conditions/': {
      id: '/_nft/terms-and-conditions/'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions/'
      preLoaderRoute: typeof NftTermsAndConditionsIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/project-overview/': {
      id: '/_nft/project-overview/'
      path: '/project-overview'
      fullPath: '/project-overview/'
      preLoaderRoute: typeof NftProjectOverviewIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/orbit/': {
      id: '/_nft/orbit/'
      path: '/orbit'
      fullPath: '/orbit/'
      preLoaderRoute: typeof NftOrbitIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/open-ai/': {
      id: '/_nft/open-ai/'
      path: '/open-ai'
      fullPath: '/open-ai/'
      preLoaderRoute: typeof NftOpenAiIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/minted/': {
      id: '/_nft/minted/'
      path: '/minted'
      fullPath: '/minted/'
      preLoaderRoute: typeof NftMintedIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/lunar-origins/': {
      id: '/_nft/lunar-origins/'
      path: '/lunar-origins'
      fullPath: '/lunar-origins/'
      preLoaderRoute: typeof NftLunarOriginsIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/lunar-calendar/': {
      id: '/_nft/lunar-calendar/'
      path: '/lunar-calendar'
      fullPath: '/lunar-calendar/'
      preLoaderRoute: typeof NftLunarCalendarIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/features/': {
      id: '/_nft/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof NftFeaturesIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/favorites/': {
      id: '/_nft/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof NftFavoritesIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/contract-interface/': {
      id: '/_nft/contract-interface/'
      path: '/contract-interface'
      fullPath: '/contract-interface/'
      preLoaderRoute: typeof NftContractInterfaceIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/contract-events/': {
      id: '/_nft/contract-events/'
      path: '/contract-events'
      fullPath: '/contract-events/'
      preLoaderRoute: typeof NftContractEventsIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/attributes/': {
      id: '/_nft/attributes/'
      path: '/attributes'
      fullPath: '/attributes/'
      preLoaderRoute: typeof NftAttributesIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/all/': {
      id: '/_nft/all/'
      path: '/all'
      fullPath: '/all/'
      preLoaderRoute: typeof NftAllIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/$id/': {
      id: '/_nft/$id/'
      path: '/$id'
      fullPath: '/$id/'
      preLoaderRoute: typeof NftIdIndexRouteImport
      parentRoute: typeof NftRoute
    }
    '/_nft/moontotem/$id': {
      id: '/_nft/moontotem/$id'
      path: '/moontotem/$id'
      fullPath: '/moontotem/$id'
      preLoaderRoute: typeof NftMoontotemIdRouteImport
      parentRoute: typeof NftRoute
    }
    '/_authenticated/_app/home/': {
      id: '/_authenticated/_app/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedAppHomeIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppHomeIndexRoute: typeof AuthenticatedAppHomeIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppHomeIndexRoute: AuthenticatedAppHomeIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NftRouteChildren {
  NftIndexRoute: typeof NftIndexRoute
  NftMoontotemIdRoute: typeof NftMoontotemIdRoute
  NftIdIndexRoute: typeof NftIdIndexRoute
  NftAllIndexRoute: typeof NftAllIndexRoute
  NftAttributesIndexRoute: typeof NftAttributesIndexRoute
  NftContractEventsIndexRoute: typeof NftContractEventsIndexRoute
  NftContractInterfaceIndexRoute: typeof NftContractInterfaceIndexRoute
  NftFavoritesIndexRoute: typeof NftFavoritesIndexRoute
  NftFeaturesIndexRoute: typeof NftFeaturesIndexRoute
  NftLunarCalendarIndexRoute: typeof NftLunarCalendarIndexRoute
  NftLunarOriginsIndexRoute: typeof NftLunarOriginsIndexRoute
  NftMintedIndexRoute: typeof NftMintedIndexRoute
  NftOpenAiIndexRoute: typeof NftOpenAiIndexRoute
  NftOrbitIndexRoute: typeof NftOrbitIndexRoute
  NftProjectOverviewIndexRoute: typeof NftProjectOverviewIndexRoute
  NftTermsAndConditionsIndexRoute: typeof NftTermsAndConditionsIndexRoute
  NftWalletIndexRoute: typeof NftWalletIndexRoute
}

const NftRouteChildren: NftRouteChildren = {
  NftIndexRoute: NftIndexRoute,
  NftMoontotemIdRoute: NftMoontotemIdRoute,
  NftIdIndexRoute: NftIdIndexRoute,
  NftAllIndexRoute: NftAllIndexRoute,
  NftAttributesIndexRoute: NftAttributesIndexRoute,
  NftContractEventsIndexRoute: NftContractEventsIndexRoute,
  NftContractInterfaceIndexRoute: NftContractInterfaceIndexRoute,
  NftFavoritesIndexRoute: NftFavoritesIndexRoute,
  NftFeaturesIndexRoute: NftFeaturesIndexRoute,
  NftLunarCalendarIndexRoute: NftLunarCalendarIndexRoute,
  NftLunarOriginsIndexRoute: NftLunarOriginsIndexRoute,
  NftMintedIndexRoute: NftMintedIndexRoute,
  NftOpenAiIndexRoute: NftOpenAiIndexRoute,
  NftOrbitIndexRoute: NftOrbitIndexRoute,
  NftProjectOverviewIndexRoute: NftProjectOverviewIndexRoute,
  NftTermsAndConditionsIndexRoute: NftTermsAndConditionsIndexRoute,
  NftWalletIndexRoute: NftWalletIndexRoute,
}

const NftRouteWithChildren = NftRoute._addFileChildren(NftRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  NftRoute: NftRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
