export { default as Slide1 } from './Slide1'
export { default as Slide2 } from './Slide2'
export { default as Slide3 } from './Slide3'
export { default as Slide4 } from './Slide4'
export { default as Slide5 } from './Slide5'
export { default as Slide6 } from './Slide6'
export { default as Slide7 } from './Slide7'
