/* eslint-disable quotes */
const answerList = [
  'It is certain.',
  'It is decidedly so.',
  'Without a doubt.',
  'Yes definitely.',
  'You may rely on it.',
  'As I see it, yes.',
  'Most likely.',
  'Outlook good.',
  'Yes.',
  'Signs point to yes.',
  'Yeppers.',
  'You can take it to the bank.',
  'Yas.',
  'You know it.',
  '100%.',
  'Definately.',
  'It is surely so.',
  'Yes, of course.',
  'Naturally it is so.',
  'It will be so.',
  'This is true.',
  'It is correct.',
  'Yep.',
  'Certainly.',
  'Indubitably',
  'Unquestionably.',
  'Without doubt.',
  'Indeed.',
  'Beyond a doubt.',
  'Most assuredly.',
  'Aye.',
  'Clearly.',
  'It is plain to see.',
  'Absolutely.',
  'Undoubtedly.',
  'Ja!',
  'I feel it is so.',
  'Reply hazy, try again.',
  'Please ask again later.',
  'I better not tell you now.',
  'I cannot predict now.',
  'Concentrate and ask again.',
  'The answer will come.',
  'It is unknowable.',
  'How long is a piece of string?',
  '42.',
  'It is as it was.',
  'You know the answer.',
  'I cannot say.',
  'I would not hazard a guess.',
  'Look closer at the moon.',
  'You do not want to know.',
  'If it is what you want...',
  'Ask yourself.',
  'Better leave it unanswered.',
  'It is not the right question.',
  "Don't count on it.",
  'My reply is no.',
  'My sources say no.',
  'Outlook not so good.',
  'Very doubtful.',
  'Zero chance.',
  'I doubt it.',
  'Never.',
  "Don't hold your breath.",
  'No way.',
  'No.',
  'Nah.',
  'Not in any way.',
  'Not by any means.',
  'Nope.',
  "That's a hard no.",
  "Don't even think about it.",
  "Can't see it.",
  'Forget about it.',
  'I would not recommend it.',
  'Not in a million years.',
  'I do not feel it.'
]

export default answerList
