export { default as Slide0 } from './Slide0'
export { default as Slide1 } from './Slide1'
export { default as Slide2 } from './Slide2'
export { default as Slide3 } from './Slide3'
export { default as Slide4 } from './Slide4'
export { default as Slide5 } from './Slide5'
